FROM node:18-alpine as builder

LABEL description="Frontend for MyJotts"

# Set the working directory
WORKDIR /app

COPY package.json ./ 

RUN npm install

COPY . .

RUN npm run build

EXPOSE 5173
CMD ["npm", "run", "dev"]
