FROM node:23-alpine as builder

LABEL description="Frontend for MyJotts (Dev)"

# Set the working directory
WORKDIR /app

COPY package.json ./ 
RUN npm install

COPY . .

ENV HOST=0.0.0.0
EXPOSE 5173
CMD ["npm", "run", "dev"]
