version: "3.9"

services:
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR INTERVAL=500
      - WATCHPACK_POLLING=true
      - VITE_HMR_CLIENT_PORT=5173
    command: npm run dev
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: ./portal-backend
      target: development
    container_name: backend
    env_file:
      - .env
    volumes:
      - ./portal-backend:/app # Mount code directory
      - /app/node_modules
    command: npm run start:dev
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
    ports:
      - "4000:4000"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4000/api"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  database:
    image: postgres:15-alpine
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: database
      PG_DATA: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 5s
      retries: 5

  adminer:
    container_name: activity-adminer
    restart: always
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  db_data: {}
