version: "3.9"

services:
  traefik:
    restart: always
    image: traefik:v2.10
    container_name: traefikdev
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik/traefik.yml:/traefik.yml:ro"

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontenddev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`myjotts.local`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "80:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR INTERVAL=500
      - WATCHPACK_POLLING=true
      - VITE_HMR_CLIENT_PORT=5173
    command: npm run dev -- --host
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: ./portal-backend
      target: development
    container_name: backenddev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.myjotts.local`)"
      - "traefik.http.services.backend.loadbalancer.server.port=4000"
    env_file:
      - .env
    volumes:
      - ./portal-backend:/app # Mount code directory
      - /app/node_modules
    command: npm run start:dev
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
    ports:
      - "4000:4000"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD", "wget", "--spider", "-q", "http://api.myjotts.local:4000/api"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  database:
    image: postgres:15-alpine
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: database
      PG_DATA: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 5s
      retries: 5

  adminer:
    container_name: activity-adminer
    restart: always
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  db_data: {}
