version: "3"

tasks:
  dev:build:
    desc: Builds docker container
    cmds:
      - docker-compose -f docker-compose.dev.yml build --no-cache

  dev:start:
    desc: starts all docker containers as background services to enable local dev
    cmds:
      - docker-compose -f docker-compose.dev.yml up -d

  dev:stop:
    desc: Stops dev docker container
    cmds:
      - docker-compose -f docker-compose.dev.yml down

  dev:restart:
    desc: Restarts dev docker container
    cmds:
      - docker-compose -f docker-compose.dev.yml restart nginx backend

  prod:build:
    desc: Builds docker container for production
    cmds:
      - docker-compose -f docker-compose.prod.yml build

  prod:start:
    desc: starts production docker container
    cmds:
      - docker-compose -f docker-compose.prod.yml up --build -d

  prod:stop:
    desc: Stops production container
    cmds:
      - docker-compose -f docker-compose.prod.yml down

  clean:
    desc: Clean up by removing all stopped containers and unused volumes
    cmds:
      - docker system prune -f
      - docker volume prune -f

  clean:volumes:
    desc: Remove all unused Docker volumes
    cmds:
      - docker volume rm $(docker volume ls -q)
      - docker volume rm $(docker volume ls -q -f dangling=true)

  clean:images:
    desc: Remove images
    cmds:
      - docker rmi <imageid>
      - docker image prune -a -f

  clean:cache:
    desc: Remove cache
    cmds:
      - docker builder prune -a -f

  logs:
    desc: Show logs of all containers
    cmds:
      - docker-compose logs -f backend

  docker:space:
    desc: Check how much space Docker is consuming
    cmds:
      - docker system df
