version: "3"

tasks:
  dev:build:
    desc: Builds docker container
    cmds:
      - docker-compose -f docker-compose.dev.yml build

  dev:start:
    desc: starts all docker containers as background services to enable local dev
    cmds:
      - docker-compose -f docker-compose.dev.yml up -d

  dev:stop:
    desc: Stops dev docker container
    cmds:
      - docker-compose -f docker-compose.dev.yml down

  dev:restart:
    desc: Restarts dev docker container
    cmds:
      - docker-compose -f docker-compose.dev.yml restart nginx backend

  prod:build:
    desc: Builds docker container for production
    cmds:
      - docker-compose build

  prod:start:
    desc: starts production docker container
    cmds:
      - docker-compose up -d

  prod:stop:
    desc: Stops production container
    cmds:
      - docker-compose down

  clean:
    desc: Clean up by removing all stopped containers and unused volumes
    cmds:
      - docker system prune -f
      - docker volume prune -f

  logs:
    desc: Show logs of all containers
    cmds:
      - docker-compose logs -f backend

  certbot:
    desc: Run certbot
    cmds:
      - docker-compose --profile certbot-only up certbot

  # ssl:generate:
  #   desc: Generate SSL certificates
  #   cmds:
  #     - docker-compose run --rm certbot certonly --webroot -w /var/www/certbot -d myjotts.com --dry-run -d myjotts.com
  #     # - docker-compose run certbot certonly --webroot --webroot-path=/var/www/certbot --email gabrieluche2@gmail.com --agree-tos --no-eff-email -d myjotts.com -d www.myjotts.com
  # ssl:run:
  #   desc: Run SSL certificates
  #   cmds:
  #     - docker run --rm -v /etc/letsencrypt:/etc/letsencrypt -v /var/www/certbot:/var/www/certbot certbot/certbot certonly --webroot --webroot-path=/var/www/certbot --email gabrieluche2@gmail.com --agree-tos --no-eff-email -d myjotts.com -d www.myjotts.com
