version: '3.5'

services:
  backend:
    container_name: portal-backend
    image: portal-backend
    build: .
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://admin:admin@db:5432/myjottsdb
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      - db
    # networks:
    #   - activity-moves

  db:
    container_name: portal_dbmodel
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: myjottsdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: localhost
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    # networks:
    #   - activity-moves

  adminer:
    container_name: activity-adminer
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  pgdata: {}

networks:
  activity-moves:
    driver: bridge
    name: activity-moves
