FROM node:18-alpine as development

LABEL version="1.0"
LABEL description="Production image for portal backend"

WORKDIR /usr/src/app


COPY package*.json ./

RUN npm install --only=development

COPY . .

# Add the PostgreSQL setup script
# ADD setup_database.sh /usr/src/app/setup_database.sh
# RUN chmod +x /usr/src/app//setup_database.sh
# RUN ./setup_database.sh

RUN npm run build


FROM node:18-alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

COPY . .

COPY --from=development /usr/src/app/dist ./dist

EXPOSE 4000

CMD ["node", "dist/main"]