name: Staging CI/CD

on:
  push:
    branches:
      - staging

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: cd frontend && npm install
      # - run: cd frontend && npm test
      - name: Deploy Frontend to Staging
        run: echo "Deploying frontend to staging... "

  portal-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: cd frontend && npm install
      # - run: cd frontend && npm test
      - name: Deploy Backend to Staging
        run: echo "Deploying backend to staging... "
